keep-open
autofit-larger=80%x80%
profile=high-quality
video-sync=display-resample
interpolation
# ontop=yes                 #Always on top
volume-max=100
save-position-on-quit
sub-font=SF Pro Display
# osd-font=SF Pro Display
# osd-font=Roboto
osd-font=Iosevka
