keep-open
geometry=40%x40%
autofit-larger=80%x80%
# profile=high-quality
video-sync=display-resample
interpolation
# ontop=yes                 #Always on top
volume-max=200
save-position-on-quit
sub-font=SF Pro Display
# osd-font=SF Pro Display
# osd-font=Roboto
loop-playlist=inf
osd-font=Iosevka
script-opts=osc-hidetimeout=2000
osd-bold=no
osc-font-size=16 # Adjust as needed
osc-layout=bottombar
# script-opts=osc-vidscale=no,osc-elements=playpause,timelabels
volume=100
