#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# if [[ $(xrandr -q | grep 'HDMI-A-0 connected')]]
# then
#   xrandr --output eDP --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of eDP
# bspc wm -O HDMI-A-0 eDP 
# bspc monitor eDP -d 6 7 8 9 10 
# bspc monitor HDMI-A-0 -d 1 2 3 4 5
# else
# bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10 
# fi

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then xrandr --output eDP --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of eDP && bspc wm -O HDMI-A-0 eDP && bspc monitor eDP -d 6 7 8 9 10 && bspc monitor HDMI-A-0 -d 1 2 3 4 5; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi

 
bspc config border_width        1
bspc config window_gap          2
bspc config focused_border_color "81A1C1"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
greenclip daemon &
polybar -r example &
polybar -r external &
dunst &
picom &
numlockx &
feh --bg-fill /home/chris/Pictures/wallpapers/wallpaper.jpg &

# bspc rule -a feh state=floating 
bspc rule -a zoom state=floating center=on follow=on
bspc rule -a Catfish state=floating center=on 
bspc rule -a "Mathpix Snipping Tool - Snip View"  state=floating center=on 

# 2024-01-26 Fri 23:56:12
bspc config right_padding 0
bspc config bottom_padding 0

