#! /bin/sh
setxkbmap latam 
xmodmap ~/.Xmodmap 

exec > /tmp/bspwmrc.log 2>&1
set -x

(sleep 0.5; for d in $(bspc query -D); do bspc desktop "$d" -l monocle; done) &



# if [[ $(xrandr -q | grep 'HDMI-A-0 connected')]]
# then
#   xrandr --output eDP --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of eDP
# bspc wm -O HDMI-A-0 eDP 
# bspc monitor eDP -d 6 7 8 9 10 
# bspc monitor HDMI-A-0 -d 1 2 3 4 5
# else
# bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10 
# fi

# if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then xrandr --output eDP --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --auto --rotate normal --right-of eDP && bspc wm -O HDMI-A-0 eDP && bspc monitor eDP -d 6 7 8 9 10 && bspc monitor HDMI-A-0 -d 1 2 3 4 5; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi
# if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then xrandr --output eDP --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --auto --rotate normal --left-of eDP && bspc wm -O HDMI-A-0 eDP && bspc monitor eDP -d 6 7 8 9 10 && bspc monitor HDMI-A-0 -d 1 2 3 4 5; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi
# if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then xrandr --output eDP --mode 1366x768 --rotate normal --output HDMI-A-0 --primary --auto --rotate normal --right-of eDP && bspc wm -O eDP HDMI-A-0 && bspc monitor eDP -d 1 2 3 4 5 && bspc monitor HDMI-A-0 -d 6 7 8 9 10; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi
# if [[ $(xrandr -q | grep -e 'HDMI-A-0 connected' -e 'eDP') ]]; then xrandr --output eDP --mode 1366x768 --rotate normal --output HDMI-A-0 --primary --auto --rotate normal --right-of eDP && bspc monitor eDP -d 1 2 3 4 5 && bspc monitor HDMI-A-0 -d 6 7 8 9 10; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi
# # Para activar solo segundo monitor -- no funciona muy bien
# if xrandr --listmonitors | grep 'HDMI-A-0' && ! xrandr --listmonitors | grep -q 'eDP'; then xrandr --output HDMI-A-0 --primary --auto && bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10 && bspc monitor eDP -r ; fi
 
# if xrandr -q | grep -q 'HDMI-A-0 connected'; then if xrandr --listmonitors | grep -q 'HDMI-A-0' && ! xrandr --listmonitors | grep -q 'eDP'; then xrandr --output HDMI-A-0 --primary --auto && bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10 && bspc monitor eDP -r; else xrandr --output eDP --mode 1366x768 --rotate normal --output HDMI-A-0 --primary --auto --rotate normal --right-of eDP && bspc monitor eDP -d 1 2 3 4 5 && bspc monitor HDMI-A-0 -d 6 7 8 9 10; fi; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi

# on top
# if xrandr -q | grep -q 'HDMI-A-0 connected'; then if xrandr --listmonitors | grep -q 'HDMI-A-0' && ! xrandr --listmonitors | grep -q 'eDP'; then xrandr --output HDMI-A-0 --primary --auto && bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10 && bspc monitor eDP -r; else xrandr --output eDP --mode 1366x768 --rotate normal --output HDMI-A-0 --primary --auto --rotate normal --above eDP && bspc monitor eDP -d 6 7 8 9 10 && bspc monitor HDMI-A-0 -d 1 2 3 4 5; fi; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi
# vertical with laptop on the left
# if xrandr -q | grep -q 'HDMI-A-0 connected'; then if xrandr --listmonitors | grep -q 'HDMI-A-0' && ! xrandr --listmonitors | grep -q 'eDP'; then xrandr --output HDMI-A-0 --primary --auto && bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10 && bspc monitor eDP -r; else xrandr --output eDP --mode 1366x768 --rotate normal --pos 0x832 --output HDMI-A-0 --primary --auto --rotate left --pos 1366x0 && bspc monitor eDP -d 1 2 3 4 5 && bspc monitor HDMI-A-0 -d 6 7 8 9 10; fi; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi

if [[ $(xrandr -q | grep '^HDMI-A-0 connected') ]]; then xrandr --output eDP --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --auto --rotate normal --left-of eDP && bspc wm -O HDMI-A-0 eDP && bspc monitor eDP -d 6 7 8 9 10 && bspc monitor HDMI-A-0 -d 1 2 3 4 5; else bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10; fi

wmname LG3D # this is for java to not missbehave
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width        1
bspc config window_gap		3
# bspc config focused_border_color "#00FF00"
bspc config focused_border_color "#ffffff"
# bspc config focused_border_color "#268bd2"
bspc config pointer_motion_interval 25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus any

# sxhkd &
# redshift &
greenclip daemon &

pkill -x polybar 2>/dev/null || true
polybar -r example &
polybar -r external &
pgrep -x dunst >/dev/null || dunst &
# picom --experimental-backends &
pgrep -x picom >/dev/null || picom -b &
numlockx &

#light-locker &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/* &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/bttf.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/monument-valley.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/arnold.jpg &
# feh --bg-fill $HOME/Pictures/wallpapers/wallpaper.png &
# feh --bg-fill $HOME/Pictures/wallpapers/wallpaper0.jpg &
# feh --bg-max $HOME/Pictures/wallpapers/grothendieck.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/mont.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/kali.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/wallhaven.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/wallpaper-aulas-b.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/road2.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/nevada.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/kurz3.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/Galaxies.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/drawn-landscape-2.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/ubuntu-wallpaper.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/pexels-rpnickson-2559941.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/beau.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/joli-arch.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/black-arch.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/blue-arch.png &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/wallpaper-arch-blue.jpg &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/fuji.png &
feh --bg-fill --randomize $HOME/Pictures/wallpapers/peace.png &

bspc rule -a feh state=floating 
# bspc rule -a zoom state=floating center=on
bspc rule -a Catfish state=floating center=on 
bspc rule -a Alacritty state=floating center=on 
# bspc rule -a Zathura state=floating center=on 
# bspc rule -a Evince state=fullscreen 
bspc rule -a "Mathpix Snipping Tool - Snip View"  state=floating center=on 
bspc rule -a "pavucontrol"  state=floating center=on 
bspc rule -a "Engrampa"  state=floating center=on 
bspc rule -a "Yad"  state=floating center=on 
bspc rule -a "Display"  state=floating center=on 
bspc rule -a "mpv"  state=floating center=on 
bspc rule -a "sumatrapdf.exe" desktop=^2
bspc rule -a "obsidian" desktop=^8
bspc rule -a "Code" desktop=^7
bspc rule -a "zoom" state=floating
bspc rule -a "webex" state=floating
bspc rule -a "Webex" state=floating
bspc rule -a "Peek" state=floating
bspc rule -a "Geogebra" state=floating
bspc rule -a "Rofi" state=floating border=off sticky=on layer=above
bspc rule -a "MEGAsync" state=floating center=on 
bspc rule -a "megasync" state=floating center=on
bspc rule -a "Inkscape" state=floating

# 2024-01-26 Fri 23:56:12
bspc config right_padding 0
bspc config bottom_padding 0

# 2026-01-03
# Mouse settings
$HOME/Documents/scripts/mouse-sensitivity.sh &
$HOME/Documents/scripts/unclutter-mouse.sh &

# 2024-08-12
# Set shadow for floating windows
$HOME/shadow-script.sh &
bspc query -N -n focused | while read -r win_id; do
  xprop -id "$win_id" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1
done


# xset s off -dpms &
# noblank
#



