;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

; See this for colors transparency
; https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4

[colors]
; background = #BF282A2E
background = #bf0d0c0c
; background = #bf000000
background-alt = #373B41
; foreground = #C5C8C6
foreground = #d1d1d1
; primary = #88c0d0
; primary = #88d09a
primary =#63b1ff
secondary = #a3be8c
alert = #A54242
disabled = #707880

[bar/example]
monitor = eDP
width = 100%
height = 20pt
radius = 0
offset-y = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 =Iosevka:size=11.55;3
; font-0 =Iosevka Light:size=11.55;3
; font-0 =Google Sans Code:size=11.55;3
; font-0 =SF Pro Display:size=13;3
font-1 = FiraCode Nerd Font:size=12;1
font-2 =Iosevka:size=9;3

modules-left = xworkspaces
modules-right = systray memory cpu eth wlan pulseaudio battery date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-name = bspwm
; wm-restack = generic
wm-restack = bspwm
; wm-restack = i3

;override-redirect = true
;
[bar/external]
monitor = HDMI-A-0
; modules-right = pulseaudio battery date
; modules-left = xworkspaces
inherit = bar/example

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
label-monitor = %name%
label-focused = %name%
label-occupied = %name%
label-urgent = %name%!
label-empty = %name%

[module/systray]
type = internal/tray
; format-margin = 8pt
tray-spacing = 9pt

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

;[module/filesystem]
;type = internal/fs
;interval = 25

;mount-0 = /

;label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

;label-unmounted = %mountpoint% not mounted
;label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
interval=2
format-volume-prefix = "󰕾 "
; format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%
; label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/battery]
type = internal/battery
; label-discharging = %{F#63b1ff}Bat%{F-} %percentage%%
; label-discharging = %{F#ffffff}󰁹%{F-} %percentage%%
; label-discharging = 󰁹 %percentage%%
label-discharging = 󰁹%{O4}%percentage%
; format-discharging = <label-discharging>
; label-low = %{F#ff3131}󰂃%{O4}%{F-}%percentage%
label-low = %{F#ff3131}󰂃%{O4}%percentage%
;label-full = %{F#90EE90}FULL%{F-} 
label-charging = %{F#90EE90}󰂄%{O4}%percentage%
format-low = <label-low><animation-low>
animation-low-0 = %{F#ff3131}%{F-}
low-at = 15
full-at = 100
battery = BAT1
adapter = ACAD
poll-interval = 2

;[module/xkeyboard]
;type = internal/xkeyboard
;blacklist-0 = num lock
;
;label-layout = %layout%
;label-layout-foreground = ${colors.primary}
;
;label-indicator-padding = 2
;label-indicator-margin = 1
;label-indicator-foreground = ${colors.background}
;label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM"
format-prefix-foreground = ${colors.disabled}
label = %{O1}%percentage_used:3%%
label-foreground = ${colors.disabled}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU"
format-prefix-foreground = ${colors.disabled}
label = %{O1}%percentage:3%%
label-foreground = ${colors.disabled}

[network-base]
type = internal/network
interval = 1
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} 

[module/wlan]
inherit = network-base
interface-type = wireless

# This keeps your icon, the O10 offset, and the signal text exactly as they were
label-connected = %{A1:nmcli radio wifi off:}󰤨%{O10}%{T-}%signal%%{A}

# This keeps your disconnected icon and the "00" exactly as they were
label-disconnected = %{A1:nmcli radio wifi on:}󰤫%{O10}%{T-}00%{A}

label-connected-font = 2

[module/eth]
inherit = network-base
interface-type = wired
; label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
label-connected = %{F#63b1ff}󰈀%{O4}
label-disconnected = 

[module/date]
type = internal/date
interval = 1
; date = %a %F %{F#C5C8C6}%H:%M:%S%{F-}
; date= %a %F %{F#C5C8C6}%H:%M:%S%{F-}
date= %{F#8ab4f8}%a%{F-} %F 󰥔 %{O4}%H:%M:%S
; date-alt =%a %F %{F#C5C8C6}%H:%M%{F-}
label = "%{A3:gsimplecal:}%date%%{A}"
; label-foreground = ${colors.primary}
#click-right = $HOME/.config/polybar/modules/popup-calendar.sh --popup &

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini



; [module/spotify]
; type = custom/script
; interval = 1
;
; ; icon (change or remove if you want)
; format-prefix = "󰓇 %{O3}"
; format = <label>
;
; ; manual clone:
; exec = python ~/.config/polybar/scripts/polybar-spotify/spotify_status.py -f '{song}'
;
; ; spotify green underline
; format-underline = #1db954
;
; ; optional mouse controls
; click-left = playerctl --player=spotify play-pause
; click-right = playerctl --player=spotify next
; click-middle = playerctl --player=spotify previous


[bar/pdftabs]
inherit = bar/example
monitor = HDMI-A-0
background = #cc000000
offset-y = 20pt
enable-ipc = true 
; enable-struts = false

modules-left = zathura-tabs
modules-right =
modules-center = 

[module/zathura-tabs]
type = custom/script
exec = $HOME/Documents/scripts/polytabs.sh
interval = 0.1
format-font = 3
